### ISSUE TITLE
finminer.exe is not working

### ISSUE THREAD

**Issue by Credo999** [FinMiner/FinMiner#2]
2018-06-01 11:42:42: <info> Version 2.0.5
2018-06-01 11:42:42: <error> NVML error: failed to get device handle by PCI: 0:1:0
2018-06-01 11:42:42: <info> Single device detected
2018-06-01 11:42:42: <info> GPU#0: Platform: CUDA, Name: GeForce GTX 1060 6GB, 6144 MB available
2018-06-01 11:42:42: <fatal> Failed to open configuration file. File not found: -a

**Comment by FinMiner** [comment]
How do you run finminer.exe? There is no such option as "-a", miner thinks it is a name of configuration file.

**Comment by meskone1224** [comment]
i keep getting wallet not found in config

here is a copy of config file

; FinMiner configuration file.

; Address to send funds to.
;wallet= 0xD0Dc8bbb0d7b1260D4458E36415b40ae43F81A45

; Payment ID (for exchange accounts). Otherwise do not set up or leave empty.
;paymentId=

; (Optional) Mining algorithm.
; Supported values: Ethash, Cryptonight
;algorithm= Ethash

; (Optional) Coin to mine.
; Supported values: ETH, ETC, XMR, ETN.
;coin= ETC

; (Optional) Rig (worker) name.
;rigName= 

; (Optional) Email to send notifications to (for nanopool).
;email= 

; (Optional) Mining pools. By default nanopool is used.
;pool1 = etc-us-east1.nanopool.org:19999

**Comment by FinMiner** [comment]
I see default configuration file is a bit discouraging. ";" means start of a commented line in ini file format. Please uncomment your wallet line, instead of
`;wallet= 0xD0Dc8bbb0d7b1260D4458E36415b40ae43F81A45`
put
`wallet= 0xD0Dc8bbb0d7b1260D4458E36415b40ae43F81A45`

**Comment by haydut023** [comment]
hi i have similar problem could you help me?

version 2.0.5
2018-06-18 NVML error failed to get device handle by PCI : 0:1:0
using default configration file  : config.ini
2018-06-18 single device detected
GPU#0: platform CUDA Name Quadro M3000M 4096 mb available

after few minutes later , program closed itself.

Waiting for your valuable replies

Thanks in advance.

**Comment by topaciomad** [comment]
same here, NVML error failed to get device handle by PCI:
hope there's a solution

**Comment by toni344** [comment]
What a total waste of time with this miner!
