### ISSUE TITLE
Screwed output

### ISSUE THREAD

**Issue by jswierad** [FinMiner/FinMiner#26]
We are automating FinMiner usage and we found out, that under Linux finminer output is screwed up. First of all stdout and stderr are a mess, second - the output is buffered, so it prevents us from easily reading it line by line. 

Unfortunately there is no code available so we cannot suggest any changes, but hopefully you can figure it out. 

cheers.

**Comment by FinMiner** [comment]
Buffered output is better for us because it is faster and we can avoid some latency problems with it. You can either read log file instead of stdout and stderr either use our new rebranded miner version called [nanominer](https://github.com/nanopool/nanominer/) which supports [BoringAPI](https://github.com/nanopool/BoringAPI) for rigs monitoring which is a good alternative to logs parsing.
