### ISSUE TITLE
email / password by pasc / nanopool

### ISSUE THREAD

**Issue by RomanF75** [FinMiner/FinMiner#27]
hello

is there any Problems known with password by pascal/nanopool

I can't change my payout Limit.

regards
Roman

**Comment by FinMiner** [comment]
There are no known problems yet. Did you uncomment email option in configuration file?

**Comment by RomanF75** [comment]
Yes I Have with
email=xxxx@xxx.xxx
I also do not receive offline emails
Regards
Roman

**Comment by tmagomedov** [comment]
I see. Please provide your account to our support team: support@miner.finom.io
Will look what's happening on pool side with email.

**Comment by FinMiner** [comment]
I see. Could you please email your Pascal account and problem description to our support team? support@miner.finom.io
Will see what does pool see as an email from it's side.

**Comment by FinMiner** [comment]
Checked everything, seems like it's a configuration issue. Please use separate option for paymentid in config file, not wallet=account.paymentid format. Such undocumented configuration surprisingly works but unfortunately email is skipped due to broken format. Please update if setting paymentid on separate option helps.
