### ISSUE TITLE
Virus alert

### ISSUE THREAD

**Issue by DeGraafSoftware** [FinMiner/FinMiner#3]
Hi there,

I was trying to install the finminer, but Windows Defender detects a virus: "Trojan:Win32/Bitrep.A" and deletes it immediately.

What to do? Can you make it Defender proof, I'm very anxious about this kind of warnings.

**Comment by FinMiner** [comment]
Hi!
WIndows Defender issue was fixed with malware database update version 1.269.888.0 of June 8. To prevent such issues in future you also can use a workaround by adding an exceptionto WIndows Defender for specific application https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-defender-antivirus
